name: Deploy Imagenes API to Azure

on:
  push:
    branches:
      - main

env:
  REGISTRY: imagenesapiregistry.azurecr.io
  IMAGE_NAME: imagenes-api
  RESOURCE_GROUP: oncovista-rg
  CONTAINER_APP_NAME: imagenes-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:latest .
        docker push $REGISTRY/$IMAGE_NAME:latest

    - name: Redeploy latest image to Azure Container App
      run: |
        az containerapp update \
          --name $CONTAINER_APP_NAME \
          --resource-group $RESOURCE_GROUP \
          --image $REGISTRY/$IMAGE_NAME:latest